// tests/unit/workflow_release_guards.test.js
//
// #261: structural invariants of the auto-release workflow. The v0.7.12 incident
// (no Docker image, npm-ci-broken main, silently skipped develop sync, fictional
// release notes) traced to four defects in dependency-update.yml. Each invariant
// below locks one fix in place so a refactor cannot silently reintroduce the
// failure mode. Mirrors the text-parsing guard pattern (knip_config / port_alignment
// / compose_profile_sync).
//
// Invariants:
//   (a) the App-token step runs BEFORE any checkout, EVERY checkout step
//       authenticates with it (a later unauthenticated checkout would rewrite
//       the persisted credential back to GITHUB_TOKEN), and every checkout
//       carries an EXPLICIT `persist-credentials: true` (#262): the persisted
//       App credential authenticates the pushes, so it must not depend on the
//       upstream default surviving the next checkout major
//   (b) no token-in-URL auth anywhere (x-access-token in a remote URL)
//   (c) the bump step resyncs package-lock.json after version:bump and before
//       the commit that snapshots the release
//   (d) no `} || {` compound guard anywhere (explicit if control flow required)
//   (e) the Release action runs only AFTER the ci-cd watch guard (anchored on
//       the `gh run watch` behavior, not on display names)
//   (f) the release body computes the tool count; no hardcoded count literal
//   (g) behavioral: package-lock.json root version fields agree with
//       package.json (catches a stale-lock bump from ANY path, including the
//       manual release lane, via the mandatory pre-commit test run)
//   (h) absence guard (#266): the retired auto-release-on-dependency.yml lane
//       must stay retired. Three prongs: the file must not exist; no TRACKED
//       file under the regeneration surface (.claude/**, .github/**) may name
//       the lane (governance text is periodically regenerated by forge-adapt,
//       so a text-only cleanup could be silently undone); and, rename-proof,
//       no workflow may use a workflow_run trigger at all (the retired lane's
//       mechanism), so resurrecting it under a new filename is also loud.
//       Scanning is git-tracked-only via git grep: untracked local files
//       (notes, logs, data) can never fail the pre-commit run, and historical
//       records outside .claude/.github may name the lane factually.
//
// Run: node tests/unit/workflow_release_guards.test.js

import assert from 'assert';
import { readFileSync, readdirSync, existsSync } from 'fs';
import { execFileSync } from 'child_process';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const WORKFLOW = join(ROOT, '.github', 'workflows', 'dependency-update.yml');

let passed = 0;
let failed = 0;
function check(label, fn) {
  try { fn(); console.log(`  ok: ${label}`); passed++; }
  catch (err) { console.error(`  FAIL: ${label} -> ${err.message}`); failed++; }
}

// Split a workflow into step blocks: each block starts at a "- name:" line.
// Text before the first step (triggers, permissions) is dropped.
function stepBlocks(text) {
  const parts = text.split(/\n(?=\s+- name: )/);
  return parts.filter((p) => /^\s+- name: /.test(p) || /(^|\n)\s+- name: /.test(p)).slice(0);
}

// (a) App token generated before any checkout; every checkout uses it AND
// carries an explicit `persist-credentials: true` (#262): the persisted App
// credential is what authenticates the later pushes to main, so disabling
// persistence (in any YAML spelling) breaks the release exactly like a
// missing `token:`, and relying on the upstream default is pin-fragile.
// Comment lines are stripped before matching so prose ABOUT the setting can
// neither satisfy nor trip the detector.
function withoutComments(block) {
  return block.split('\n').filter((l) => !/^\s*#/.test(l)).join('\n');
}
function appTokenAuthenticatesEveryCheckout(text) {
  const blocks = stepBlocks(text);
  const tokenIdx = blocks.findIndex((b) => b.includes('create-github-app-token'));
  const checkouts = blocks
    .map((b, i) => ({ b: withoutComments(b), i }))
    .filter(({ b }) => b.includes('uses: actions/checkout@'));
  if (tokenIdx === -1 || checkouts.length === 0) return false;
  return checkouts.every(({ b, i }) =>
    i > tokenIdx &&
    b.includes('token: ${{ steps.token.outputs.token }}') &&
    /persist-credentials:\s*['"]?true\b/i.test(b) &&
    !/persist-credentials:\s*['"]?false\b/i.test(b));
}

// (b) Token-in-URL auth writes the secret into .git/config; banned.
function hasTokenInUrlAuth(text) {
  return text.includes('x-access-token:');
}

// (c) The bump step must resync the lockfile after bumping and before committing.
function bumpResyncsLockfile(text) {
  const bumpStep = stepBlocks(text).find((b) => b.includes('npm run version:bump'));
  if (!bumpStep) return false;
  const bump = bumpStep.indexOf('npm run version:bump');
  const resync = bumpStep.indexOf('npm install --package-lock-only');
  const commit = bumpStep.indexOf('git commit');
  return resync > bump && commit > resync;
}

// (d) The `} || {` compound guard suppresses errexit inside the left group and
// produced the false "Develop fast-forwarded" success in run 28632676467.
function hasCompoundGuardPattern(text) {
  return /\}\s*\|\|\s*\{/.test(text);
}

// (e) The Release action must come after the guard that watches the ci-cd run
// on the new tag. Anchored on behavior-bearing text (`gh run watch` and the
// release action's `uses:` line), not on renameable step display names.
function releaseGatedByGuard(text) {
  const watchIdx = text.indexOf('gh run watch');
  const releaseIdx = text.indexOf('uses: softprops/action-gh-release');
  return watchIdx !== -1 && releaseIdx !== -1 && watchIdx < releaseIdx;
}

// (f) A hardcoded tool count (the "62 MCP tools" drift) is banned; the body must
// interpolate the computed count.
function hardcodedToolCount(text) {
  return /\b\d+\s+(MCP\s+)?tools\b/i.test(text);
}
function computesToolCount(text) {
  return text.includes('steps.bump.outputs.tool_count');
}

// (g) Behavioral lock agreement: catches a stale-lock version bump from ANY
// lane (auto-release or the manual release skill) when the mandatory pre-commit
// unit suite runs on the bumped tree.
function lockfileAgreesWithPackageJson(root) {
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
  const lock = JSON.parse(readFileSync(join(root, 'package-lock.json'), 'utf8'));
  return lock.version === pkg.version && lock.packages[''].version === pkg.version;
}

// (h) Absence guard for the lane retired by #266.
const RETIRED_WORKFLOW = join('.github', 'workflows', 'auto-release-on-dependency.yml');
// Bans the retired workflow's MACHINE IDENTIFIER in any case or
// hyphen/underscore variant (the realistic resurrection vector: a filename or
// file reference). Deliberately does NOT match the space-separated concept
// phrase "auto-release on dependency update", which legitimately names Lane B
// itself; prose resurrection without a mechanism is covered by the
// workflow_run prong below.
const RETIRED_LANE_PATTERN = 'auto[-_]release[-_]on[-_]dependency';
function referencesRetiredLane(text) {
  return new RegExp(RETIRED_LANE_PATTERN, 'i').test(text);
}
// git grep over TRACKED files only, scoped to the regeneration surface. Exits
// 1 when nothing matches (clean); any other failure propagates loudly.
function findRetiredLaneReferences(root) {
  try {
    const out = execFileSync('git',
      ['grep', '-lIiE', RETIRED_LANE_PATTERN, '--', '.claude', '.github'],
      { cwd: root, encoding: 'utf8' });
    return out.split('\n').filter(Boolean);
  } catch (err) {
    if (err.status === 1) return [];
    throw err;
  }
}
// Rename-proof prong: the retired lane's mechanism was a workflow_run listener
// releasing on CI/CD completion. No workflow may use that trigger, whatever
// its filename; dependency-update.yml is the only auto-release writer to main.
function workflowsUsingWorkflowRun(root) {
  const dir = join(root, '.github', 'workflows');
  return readdirSync(dir)
    .filter((f) => f.endsWith('.yml') || f.endsWith('.yaml'))
    .filter((f) => /(^|\n)\s*workflow_run\s*:/.test(readFileSync(join(dir, f), 'utf8')));
}

// (i) #297: the BUMPED tree is re-verified (build + tool-count drift guard +
// unit suite) AFTER the bump step and BEFORE the merge/tag step, so the commit
// that reaches main and gets the immutable tag is not the one commit CI skipped.
// The merge/tag step is anchored on `git tag -a` (unique to it; the sync step
// also runs `git merge --ff-only`, so merge alone is ambiguous).
function reverifiesBumpedTree(text) {
  const blocks = stepBlocks(text);
  const bumpIdx = blocks.findIndex((b) => b.includes('npm run version:bump'));
  const tagIdx = blocks.findIndex((b) => b.includes('git tag -a'));
  const reverifyIdx = blocks.findIndex((b) =>
    b.includes('npm run build') &&
    b.includes('npm run tool-count') &&
    b.includes('npm run test:unit-js') &&
    !/continue-on-error:\s*true/i.test(b));  // a neutered step must not satisfy it
  return bumpIdx !== -1 && tagIdx !== -1 && reverifyIdx !== -1 &&
    reverifyIdx > bumpIdx && reverifyIdx < tagIdx;
}

// (#298 reverted by maintainer decision: the @actual-app/api update lane is
// deliberately NOT gated on npm audit, so there is no blocking-audit invariant.
// Updating the API is independent of the rest of the dependency tree.)

// (k) #299: the fallback sync-PR `gh pr create` authenticates with the APP token,
// command-scoped via `GH_TOKEN="$APP_TOKEN"`, NOT the step-level github.token, so
// the sync PR actually triggers CI. Scoped to the create step (the block that
// contains `gh pr create --base develop`); the read-only github.token watcher and
// the deliberate github.token develop push must not be required to change.
function syncPrCreateUsesAppToken(text) {
  const syncStep = stepBlocks(text).find((b) =>
    b.includes('gh pr create') && b.includes('--base develop'));
  if (!syncStep) return false;
  return /GH_TOKEN="\$APP_TOKEN"\s+gh pr create/.test(syncStep) &&
    /APP_TOKEN:\s*\$\{\{\s*steps\.token\.outputs\.token\s*\}\}/.test(syncStep);
}

// (l) #300: the version check resolves the upstream target via the `latest`
// dist-tag (`npm show <pkg> version`), never the plural `versions` list form from
// which a nightly could be selected. This is what keeps prereleases out of the
// automated train.
function usesDistTagVersionCheck(text) {
  const raw = stepBlocks(text).find((b) => b.includes('npm show @actual-app/api'));
  if (!raw) return false;
  // Strip comment lines first: the workflow's own comment names the banned
  // plural `versions` form as the counter-example, and must not trip the
  // detector (mirrors the withoutComments guard used by invariant (a)).
  const step = withoutComments(raw);
  return /npm show @actual-app\/api version\b/.test(step) &&
    !/npm show @actual-app\/api versions\b/.test(step);
}

console.log('\n[workflow-release-guards]');

const wf = readFileSync(WORKFLOW, 'utf8');

check('(a) App-token step precedes checkout; every checkout authenticates with it and keeps credential persistence explicitly on', () => {
  assert.ok(appTokenAuthenticatesEveryCheckout(wf),
    'create-github-app-token must run before any actions/checkout, every checkout must pass token: ${{ steps.token.outputs.token }} AND an explicit persist-credentials: true (no false in any spelling), or pushes authenticate as GITHUB_TOKEN / lose the credential and never trigger ci-cd.yml (#261 fix 2, #262)');
});

check('(b) no token-in-URL (x-access-token) auth anywhere in the workflow', () => {
  assert.ok(!hasTokenInUrlAuth(wf),
    'token-in-URL auth duplicates the credential path and risks the token surfacing in logged remote URLs; authenticate through the checkout step instead (#261 fix 2)');
});

check('(c) bump step resyncs package-lock.json between version:bump and the commit', () => {
  assert.ok(bumpResyncsLockfile(wf),
    'npm install --package-lock-only must run after npm run version:bump and before git commit in the same step, or the release commit fails npm ci (#261 fix 1)');
});

check('(d) no `} || {` compound guard anywhere (explicit if control flow)', () => {
  assert.ok(!hasCompoundGuardPattern(wf),
    'the `} || {` compound guard swallows failures under errexit and skips the sync PR (#261 fix 3)');
});

check('(e) Release action runs only after the ci-cd watch guard', () => {
  assert.ok(releaseGatedByGuard(wf),
    'gh run watch (the publish guard) must appear before uses: softprops/action-gh-release (#261 fix 5)');
});

check('(f) release body computes the tool count; no hardcoded count literal', () => {
  assert.ok(!hardcodedToolCount(wf),
    'hardcoded tool-count literal found; interpolate the computed count instead (#261 fix 4)');
  assert.ok(computesToolCount(wf),
    'release body must interpolate steps.bump.outputs.tool_count (#261 fix 4)');
});

check('(g) package-lock.json root version fields agree with package.json', () => {
  assert.ok(lockfileAgreesWithPackageJson(ROOT),
    'package-lock.json version fields disagree with package.json: a version bump was committed without npm install --package-lock-only, so npm ci will fail at this commit (#261 fix 1)');
});

check('(h) the retired auto-release-on-dependency lane stays retired', () => {
  assert.ok(!existsSync(join(ROOT, RETIRED_WORKFLOW)),
    `${RETIRED_WORKFLOW} exists; it was retired by #266 and must not be reintroduced (full rationale: the retirement note in .claude/skills/release-automation/SKILL.md)`);
  const refs = findRetiredLaneReferences(ROOT);
  assert.strictEqual(refs.length, 0,
    `governance files reference the retired auto-release lane: ${refs.join(', ')} (#266; see the retirement note in .claude/skills/release-automation/SKILL.md)`);
  const listeners = workflowsUsingWorkflowRun(ROOT);
  assert.strictEqual(listeners.length, 0,
    `workflow_run listeners found (${listeners.join(', ')}): the retired release lane's mechanism must not return under any filename (#266)`);
});

check('(i) the bumped tree is re-verified (build + tool-count + unit suite) after bump and before merge/tag', () => {
  assert.ok(reverifiesBumpedTree(wf),
    'a re-verify step running npm run build + npm run tool-count + npm run test:unit-js must sit after the version:bump step and before the git tag -a step, or the tagged commit is never validated (#297)');
});

check('(k) the sync-PR gh pr create uses the command-scoped App token, not github.token', () => {
  assert.ok(syncPrCreateUsesAppToken(wf),
    'the fallback sync PR must be created with GH_TOKEN="$APP_TOKEN" gh pr create (APP_TOKEN from steps.token.outputs.token), or the PR opened by github.token gets no CI (#299)');
});

check('(l) the version check resolves via the latest dist-tag, not the plural versions list', () => {
  assert.ok(usesDistTagVersionCheck(wf),
    'the version check must use npm show @actual-app/api version (dist-tag), never npm show ... versions (plural), or the train could auto-ship nightlies (#300)');
});

// NEGATIVE fixtures: each detector must catch its regression when reintroduced.
check('NEGATIVE (a): checkout before token step, missing token:, a second unauthenticated checkout, or persistence loss is detected', () => {
  const before = '      - name: Checkout\n        uses: actions/checkout@v4\n      - name: Generate GitHub App token\n        uses: actions/create-github-app-token@v3';
  assert.strictEqual(appTokenAuthenticatesEveryCheckout(before), false, 'checkout before token step must fail');
  const noToken = '      - name: Generate GitHub App token\n        uses: actions/create-github-app-token@v3\n      - name: Checkout\n        uses: actions/checkout@v4\n        with:\n          ref: main\n          persist-credentials: true';
  assert.strictEqual(appTokenAuthenticatesEveryCheckout(noToken), false, 'checkout without token: must fail');
  const ok = '      - name: Generate GitHub App token\n        uses: actions/create-github-app-token@v3\n      - name: Checkout\n        uses: actions/checkout@v4\n        with:\n          token: ${{ steps.token.outputs.token }}\n          persist-credentials: true';
  assert.strictEqual(appTokenAuthenticatesEveryCheckout(ok), true, 'the compliant shape must pass');
  const secondUnauthed = ok + '\n      - name: Checkout again\n        uses: actions/checkout@v4\n        with:\n          ref: develop';
  assert.strictEqual(appTokenAuthenticatesEveryCheckout(secondUnauthed), false, 'a second checkout without token: must fail');
  const noExplicitPersist = ok.replace('\n          persist-credentials: true', '');
  assert.strictEqual(appTokenAuthenticatesEveryCheckout(noExplicitPersist), false,
    'a checkout relying on the upstream persist-credentials default must fail: pin it explicitly (#262)');
  for (const spelling of ['false', '"false"', "'false'", 'False', 'FALSE']) {
    const persistOff = ok.replace('persist-credentials: true', `persist-credentials: ${spelling}`);
    assert.strictEqual(appTokenAuthenticatesEveryCheckout(persistOff), false,
      `persist-credentials: ${spelling} must fail: the persisted credential authenticates the pushes (#262)`);
  }
  const commentOnly = ok + '\n          # never set persist-credentials: false here (#262)';
  assert.strictEqual(appTokenAuthenticatesEveryCheckout(commentOnly), true,
    'a comment MENTIONING persist-credentials: false must not trip the detector');
});

check('NEGATIVE (b): a reintroduced x-access-token URL is detected', () => {
  assert.strictEqual(hasTokenInUrlAuth('git remote set-url origin "https://x-access-token:${T}@github.com/o/r.git"'), true);
  assert.strictEqual(hasTokenInUrlAuth('git push origin main'), false);
});

check('NEGATIVE (c): a resync outside the bump step, or after the commit, is detected', () => {
  const outside = '      - name: Bump\n        run: |\n          npm run version:bump -- patch\n          git commit -m x\n      - name: Later\n        run: npm install --package-lock-only';
  assert.strictEqual(bumpResyncsLockfile(outside), false, 'resync in a different step must fail');
  const after = '      - name: Bump\n        run: |\n          npm run version:bump -- patch\n          git commit -m x\n          npm install --package-lock-only';
  assert.strictEqual(bumpResyncsLockfile(after), false, 'resync after the commit must fail');
  const ok = '      - name: Bump\n        run: |\n          npm run version:bump -- patch\n          npm install --package-lock-only\n          git commit -m x';
  assert.strictEqual(bumpResyncsLockfile(ok), true, 'the compliant order must pass');
});

check('NEGATIVE (d): a reintroduced `} || {` compound guard is detected', () => {
  assert.strictEqual(hasCompoundGuardPattern('{\n  git merge --ff-only main\n} || {\n  echo fallback\n}'), true);
  assert.strictEqual(hasCompoundGuardPattern('if ! git merge --ff-only main; then\n  echo fallback\nfi'), false);
});

check('NEGATIVE (e): a Release action reordered before the watch guard is detected', () => {
  const fixture = 'uses: softprops/action-gh-release@v3\n...\ngh run watch "$RUN_ID" --exit-status';
  assert.strictEqual(releaseGatedByGuard(fixture), false);
});

check('NEGATIVE (f): a reintroduced hardcoded count literal is detected', () => {
  assert.strictEqual(hardcodedToolCount('All 62 MCP tools validated'), true);
  assert.strictEqual(hardcodedToolCount('all 71 tools registered'), true);
  assert.strictEqual(hardcodedToolCount('All ${{ steps.bump.outputs.tool_count }} MCP tools validated'), false);
});

check('NEGATIVE (h): resurrected identifiers and workflow_run listeners are detected; the Lane B concept phrase is not', () => {
  assert.strictEqual(referencesRetiredLane('uses: ./.github/workflows/auto-release-on-dependency.yml'), true);
  assert.strictEqual(referencesRetiredLane('the Auto-Release-On-Dependency workflow'), true);
  assert.strictEqual(referencesRetiredLane('AUTO_RELEASE_ON_DEPENDENCY=true'), true);
  assert.strictEqual(referencesRetiredLane('Lane B (Auto-release on dependency) is installed'), false,
    'the space-separated Lane B concept phrase must stay legal');
  assert.strictEqual(referencesRetiredLane('dependency-update.yml is the only auto-release lane'), false);
  const wfFixture = 'on:\n  workflow_run:\n    workflows: ["CI/CD Pipeline"]\n    types: [completed]';
  assert.strictEqual(/(^|\n)\s*workflow_run\s*:/.test(wfFixture), true, 'a workflow_run trigger fixture must be detected');
  assert.strictEqual(/(^|\n)\s*workflow_run\s*:/.test('on:\n  push:\n    branches: [main]'), false);
});

check('NEGATIVE (i): re-verify missing, or placed after the tag step, is detected', () => {
  const bump = '      - name: Bump\n        run: |\n          npm run version:bump -- patch\n          npm install --package-lock-only\n          git commit -m x';
  const reverify = '      - name: Re-verify\n        run: npm run build && npm run tool-count && npm run test:unit-js';
  const tag = '      - name: Merge and tag\n        run: |\n          git merge --ff-only "$BRANCH"\n          git tag -a "v1"';
  assert.strictEqual(reverifiesBumpedTree(bump + '\n' + reverify + '\n' + tag), true, 'the compliant order must pass');
  assert.strictEqual(reverifiesBumpedTree(bump + '\n' + tag), false, 'no re-verify step must fail');
  assert.strictEqual(reverifiesBumpedTree(bump + '\n' + tag + '\n' + reverify), false, 're-verify after the tag step must fail');
  const partial = '      - name: Re-verify\n        run: npm run build && npm run test:unit-js';
  assert.strictEqual(reverifiesBumpedTree(bump + '\n' + partial + '\n' + tag), false, 'a re-verify missing tool-count must fail');
  const neutered = '      - name: Re-verify\n        continue-on-error: true\n        run: npm run build && npm run tool-count && npm run test:unit-js';
  assert.strictEqual(reverifiesBumpedTree(bump + '\n' + neutered + '\n' + tag), false, 'a continue-on-error re-verify step must fail (it never blocks the tag)');
});

check('NEGATIVE (k): a sync-PR create on github.token, or without the APP_TOKEN env, is detected', () => {
  const appTokenEnv = '        env:\n          GH_TOKEN: ${{ github.token }}\n          APP_TOKEN: ${{ steps.token.outputs.token }}\n';
  const ok = '      - name: Sync\n' + appTokenEnv + '        run: |\n          elif GH_TOKEN="$APP_TOKEN" gh pr create --base develop --head main \\\n            --title t; then';
  assert.strictEqual(syncPrCreateUsesAppToken(ok), true, 'the compliant command-scoped App token must pass');
  const plain = '      - name: Sync\n' + appTokenEnv + '        run: |\n          elif gh pr create --base develop --head main \\\n            --title t; then';
  assert.strictEqual(syncPrCreateUsesAppToken(plain), false, 'an unscoped gh pr create (github.token) must fail');
  const noEnv = '      - name: Sync\n        env:\n          GH_TOKEN: ${{ github.token }}\n        run: |\n          elif GH_TOKEN="$APP_TOKEN" gh pr create --base develop --head main; then';
  assert.strictEqual(syncPrCreateUsesAppToken(noEnv), false, 'a create referencing $APP_TOKEN without the APP_TOKEN env mapping must fail');
  // Non-interference: a read-only github.token watcher block must not affect the result.
  const watcher = '      - name: Watch\n        env:\n          GH_TOKEN: ${{ github.token }}\n        run: gh run watch "$RUN_ID" --exit-status';
  assert.strictEqual(syncPrCreateUsesAppToken(watcher + '\n' + ok), true, 'a github.token watcher elsewhere must not trip the sync-PR detector');
});

check('NEGATIVE (l): a plural `versions` list lookup is detected', () => {
  const distTag = '      - name: Check\n        run: LATEST=$(npm show @actual-app/api version)';
  assert.strictEqual(usesDistTagVersionCheck(distTag), true, 'the dist-tag form must pass');
  const plural = '      - name: Check\n        run: LATEST=$(npm show @actual-app/api versions --json | jq -r last)';
  assert.strictEqual(usesDistTagVersionCheck(plural), false, 'the plural versions list form must fail');
  const none = '      - name: Build\n        run: npm run build';
  assert.strictEqual(usesDistTagVersionCheck(none), false, 'no version check step must fail');
});

console.log(`\n[workflow-release-guards] Results: ${passed} passed, ${failed} failed`);
process.exit(failed > 0 ? 1 : 0);
